services:
  spark:
    image: apache/sedona:latest
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - DRIVER_MEM=8g
      - EXECUTOR_MEM=12g
    ports:
      - "8888:8888"
      - "8080:8080"
      - "8081:8081"
      - "4040:4040"
      - "7077:7077"
      - "6066:6066"