services:
  spark-master:
    image: apache/sedona:latest
    container_name: spark-master
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - DRIVER_MEM=6g
      - SPARK_MODE=master
    ports:
      - "8888:8888"
      - "8080:8080"
      - "7077:7077"
    networks:
      - spark-network

  spark-worker:
    image: apache/sedona:latest
    container_name: spark-worker
    hostname: spark-worker
    environment:
      - EXECUTOR_MEM=12g
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=//${SPARK_MASTER_IP:-spark-master}:7077
    networks:
      - spark-network
    depends_on:
      - spark-master

networks:
  spark-network:
    driver: bridge
