name: Benchmarks
on:
  pull_request: { paths: ['pyproject.toml', 'uv.lock'] }
  push: { branches: [master], paths: ['pyproject.toml', 'uv.lock', 'geospeed/**', 'scripts/**', '.github/workflows/**'] }
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allow pushing commits back to repo
    timeout-minutes: ${{ github.event_name == 'pull_request' && 10 || 60 }}
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      
      - name: Cache system packages
        uses: actions/cache@v4
        with:
          path: /var/cache/apt
          key: ${{ runner.os }}-apt-${{ hashFiles('.github/workflows/benchmark.yml') }}
          restore-keys: |
            ${{ runner.os }}-apt-
      
      - uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
      
      - name: Install GDAL and Java
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y gdal-bin libgdal-dev openjdk-11-jdk
          echo "Installed GDAL version: $(gdal-config --version)"
      
      - name: Set JAVA_HOME
        run: echo "JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64" >> $GITHUB_ENV
      - run: uv sync && mkdir -p ALKIS_TEST/test_county
      
      - name: Install geofileops for benchmarking
        run: |
          # Check system GDAL version
          GDAL_VERSION=$(gdal-config --version)
          echo "System GDAL version: $GDAL_VERSION"
          
          # Try to install geofileops, with fallback for version compatibility
          if ! uv add 'geofileops>=0.8.0'; then
            echo "Failed to install geofileops with latest GDAL bindings"
            echo "Trying with specific GDAL version constraint..."
            # Try with older GDAL bindings that match system version
            GDAL_VERSION="$GDAL_VERSION" uv add 'geofileops>=0.8.0' 'GDAL<3.9,>=3.8' || {
              echo "Could not install geofileops with compatible GDAL version"
              echo "Skipping geofileops benchmark in this run"
            }
          fi
      - run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            uv run python -c "import geopandas, pyogrio, duckdb; print('✅ OK')"
          else
            timeout 3600 uv run python scripts/benchmarks.py
            uv run python scripts/update_readme.py
            git diff --quiet readme.md || {
              git config user.email "action@github.com"
              git config user.name "GitHub Action"
              git add readme.md
              git commit -m "Update benchmarks"
              git push
            }
          fi
