name: Benchmarks
on:
  pull_request: { paths: ['pyproject.toml', 'uv.lock'] }
  push: { branches: [master], paths: ['pyproject.toml', 'uv.lock', 'geospeed/**', 'scripts/**', '.github/workflows/**'] }
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: ${{ github.event_name == 'pull_request' && 10 || 60 }}
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      
      - name: Cache system packages
        uses: actions/cache@v4
        with:
          path: /var/cache/apt
          key: ${{ runner.os }}-apt-${{ hashFiles('.github/workflows/benchmark.yml') }}
          restore-keys: |
            ${{ runner.os }}-apt-
      
      - uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
      
      - run: sudo apt-get update -qq && sudo apt-get install -y gdal-bin libgdal-dev
      - run: uv sync && mkdir -p ALKIS_TEST/test_county
      - run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            uv run python -c "import geopandas, pyogrio, duckdb; print('✅ OK')"
          else
            timeout 3600 uv run python scripts/benchmarks.py
            uv run python scripts/update_readme.py
            git diff --quiet README.md || {
              git config user.email "action@github.com"
              git config user.name "GitHub Action"
              git add README.md
              git commit -m "Update benchmarks"
              git push
            }
          fi
